// frontend/src/pages/transactions/ui/Transactions.vue
<template>
    <div>
        <h2>История транзакций</h2>
        <AddTransactionButton />

        <TransactionsHistory />
    </div>
</template>

<script setup lang="ts">

    import { TransactionsHistory } from '~/widgets/transaction-history';
    import { AddTransactionButton } from '~/features/edit-transaction';

</script>

// frontend/src/pages/transactions/ui/Transactions.tsx
import './Transactions.less';
import { AddTransactionButton } from '~/features/edit-transaction';
import { TransactionsHistory } from '~/widgets/transaction-history';

export const Transactions = () => {
    return <div className="transactions-page">
        <h2>История транзакций</h2>

        <TransactionsHistory />

        <div className="transactions-page__float-button">
            <AddTransactionButton />
        </div>
    </div>;
}
