// frontend/src/widgets/cash-account/ui/CashAccountList.tsx
import { observer } from 'mobx-react-lite';
import { AddCashAccount, EditableCashAccount } from '~/features/edit-cash-accounts';
import './CashAccountList.less';
import { CashAccountsStore, loadCashAccounts } from '~/entities/cash-account';
import { useEffect } from 'react';
import { AccountStatusStore } from '~/entities/account-status';

export const CashAccountList = observer(() => {
    const cashAccountStore = CashAccountsStore.getInstance();
    const accountStatusStore = AccountStatusStore.getInstance();

    useEffect(() => {
        if (accountStatusStore.isAuth) {
            loadCashAccounts();
        }
    }, [accountStatusStore.isAuth]);

    if (!accountStatusStore.isAuth) {
        return null;
    }

    return <div>
        <h3>Счета</h3>
        <div className="cash-account-list">
            {
                cashAccountStore.cashAccounts.map(cashAccount => {
                    return <EditableCashAccount
                        key={cashAccount.id}
                        cashAccount={cashAccount}
                    />
                })
            }
            <AddCashAccount />
        </div>
    </div>;
});

// frontend/src/widgets/cash-account/ui/CashAccountList.vue
<template>
    <div>
        <h3>Счета</h3>
        <div class="cash-account-list">
            <EditableCashAccount
                v-for="cashAccount in cashAccounts"
                :key="cashAccount.id"
                :cash-account="cashAccount"
            />
        </div>
        <AddCashAccount />
    </div>
</template>

<script setup lang="ts">
    import { watch } from 'vue';
    import { storeToRefs } from 'pinia';
    import { loadCashAccounts, useCashAccountsStore } from '~/entities/cash-account';
    import { useAccountStatusStore } from '~/entities/account-status';
    import { AddCashAccount } from '../../../features/edit-cash-accounts';
    import { EditableCashAccount } from '~/features/edit-cash-accounts';

    const cashAccountsStore = useCashAccountsStore();
    const { cashAccounts } = storeToRefs(cashAccountsStore);
    const accountStore = useAccountStatusStore();
    const { isAuth } = storeToRefs(accountStore);

    watch(isAuth, () => {
        if (isAuth) {
            loadCashAccounts();
        }
    }, { immediate: true });
</script>

<style>
.cash-account-list {
    display: flex;
    flex-direction: column;
    gap: 1rem;
}
</style>
