// frontend/src/features/edit-transaction/ui/AddTransactionButton.tsx
import { useCallback } from 'react';
import { Icon, IconEnum } from '~/shared/ui';

export const AddTransactionButton = () => {
    const openTransactionWidget = useCallback(() => {

    }, []);

    return <button className="btn btn--flex" onClick={openTransactionWidget}>
        <Icon iconName={IconEnum.add} />
        <span>
            Добавить
        </span>
    </button>
};

// frontend/src/features/edit-transaction/ui/AddTransactionButton.vue
<template>
    <button class="btn btn--flex" @click="openTransactionWidget">
        <Icon :icon-name="IconEnum.add" />
        <span>
            Добавить
        </span>
    </button>
</template>

<script setup lang="ts">

    import { useModal } from 'vue-final-modal';
    import EditAccountTransactionModal from './EditAccountTransactionModal.vue';
    import { Icon, IconEnum } from '~/shared/ui';

    function openTransactionWidget() {
        const { open } = useModal({
            component: EditAccountTransactionModal,
        });

        open();
    }
</script>

<style>

</style>
