// frontend/src/features/edit-cash-accounts/ui/AddCashAccount.tsx
import { KeyboardEvent, useCallback, useEffect, useRef, useState } from 'react';
import {
    addCashAccount,
} from '../lib/update-cash-account.ts';
import { Icon, IconEnum } from '~/shared/ui';
import './AddCashAccount.less';

export function AddCashAccount() {
    const inputRef = useRef<HTMLInputElement>(null);
    const [showForm, setFormVisibility] = useState(false);

    const showOrHideForm = useCallback(() => {
        setFormVisibility(!showForm);
    }, [showForm]);

    const onSubmit = useCallback(() => {
        const newValue = inputRef.current?.value;

        if (newValue) {
            addCashAccount(newValue);
        }

        setFormVisibility(false);
    }, []);

    const onKeyDown = useCallback((event: KeyboardEvent<HTMLInputElement>) => {
        if (event.code === 'Escape') {
            setFormVisibility(false);
        }
        if (event.code === 'Enter') {
            onSubmit();
        }
    }, [onSubmit]);

    useEffect(() => {
        if (showForm && inputRef.current) {
            inputRef.current?.focus();
        }
    }, [inputRef, showForm]);

    return <div className="add-cash-account">
        {
            showForm
                ? <form
                    className="add-cash-account__form"
                    onSubmit={onSubmit}
                >
                    <input
                        ref={inputRef}
                        className="add-cash-account__input"
                        name="name"
                        onKeyDown={onKeyDown}
                    />

                    <button className="btn">
                        Сохранить
                    </button>
                </form>
                : <button className="btn btn--flex" onClick={showOrHideForm}>
                    <Icon iconName={IconEnum.add} />
                    <span>
                        Добавить
                    </span>
                </button>
        }
    </div>;
}

// frontend/src/features/edit-cash-accounts/ui/AddCashAccount.vue
<template>
    <div class="add-cash-account">
        <button v-if="!showForm" class="btn btn--flex" @click="showOrHideForm">
            <Icon :icon-name="IconEnum.add" />
            <span>
                Добавить
            </span>
        </button>
        <form
            v-else
            class="add-cash-account__form"
            @submit.prevent="create"
            @keydown="onEscape"
        >
            <input
                ref="cash-account-input"
                v-model="name"
                class="add-cash-account__input"
                name="name"
            >

            <button class="btn">
                Сохранить
            </button>
        </form>
    </div>
</template>

<script setup lang="ts">
    import { nextTick, ref, useTemplateRef } from 'vue';
    import { addCashAccount } from '../lib/update-cash-account.ts';
    import { Icon, IconEnum } from '~/shared/ui';

    const showForm = ref<boolean>(false);
    const name = ref<string>('');
    const input = useTemplateRef('cash-account-input');

    function create() {
        addCashAccount(name.value);
        showForm.value = false;
    }

    function showOrHideForm() {
        showForm.value = !showForm.value;

        if (showForm.value) {
            // vue сначала рендерит список, потом позволяет обратиться к ref
            // ждем появления инпута, на который надо сфокусироваться.
            nextTick(() => {
                input.value?.focus();
            });
        }
    }

    function onEscape(event: KeyboardEvent) {
        if (event.code === 'Escape') {
            showOrHideForm();
        }
    }
</script>

<style>
.add-cash-account {
    padding: 1rem 0;
}

.add-cash-account__form {
    display: flex;
    align-items: center;
    gap: 1rem;
}

.add-cash-account__input {
    flex-grow: 1;
}
</style>
