// frontend/src/features/edit-cash-accounts/ui/EditableCashAccount.vue
<template>
    <CashAccount :cash-account="cashAccount">
        <template v-if="showForm" #name>
            <input
                ref="cash-account-input"
                v-model="name"
                name="name"
                @keydown.escape="showOrHideForm"
                @keydown.enter="save"
            >
        </template>
        <template #buttons>
            <button v-if="!showForm" class="btn btn--small btn--no-background" @click="showOrHideForm">
                <Icon :icon-name="IconEnum.edit" />
            </button>
            <div v-else class="cash-account-buttons">
                <button class="btn btn--small btn--no-background" @click="deleteItem">
                    <Icon :icon-name="IconEnum.delete" />
                </button>
                <button class="btn btn--small btn--no-background" @click="save">
                    <Icon :icon-name="IconEnum.ok" />
                </button>
            </div>
        </template>
    </CashAccount>
</template>

<script setup lang="ts">
    import { nextTick, ref, useTemplateRef } from 'vue';
    import { CashAccount } from '~/entities/cash-account';
    import { TCashAccount } from '~/shared/api';
    import { deleteCashAccount, updateCashAccount } from '../lib/update-cash-account.ts';
    import { Icon, IconEnum } from '~/shared/ui';

    type TProps = {
        cashAccount: TCashAccount
    }

    const { cashAccount } = defineProps<TProps>();

    const showForm = ref<boolean>(false);
    const name = ref<string>(cashAccount.name);
    const input = useTemplateRef('cash-account-input');

    function save() {
        updateCashAccount(cashAccount, name.value);
        showForm.value = false;
    }

    function deleteItem() {
        deleteCashAccount(cashAccount.id);
    }

    function showOrHideForm() {
        showForm.value = !showForm.value;

        if (showForm.value) {
            // vue сначала рендерит список, потом позволяет обратиться к ref
            // ждем появления инпута, на который надо сфокусироваться.
            nextTick(() => {
                input.value?.focus();
            });
        }
    }
</script>

<style>
.cash-account-buttons {
    display: flex;
    gap: 1rem;
}
</style>

// frontend/src/features/edit-cash-accounts/ui/EditableCashAccount.tsx
import { observer } from 'mobx-react-lite';
import { CashAccount } from '~/entities/cash-account';
import { TCashAccount } from '~/shared/api';
import { KeyboardEvent, useCallback, useRef, useState } from 'react';
import { deleteCashAccount, updateCashAccount } from '../lib/update-cash-account.ts';
import { Icon, IconEnum } from '~/shared/ui';
import './EditableCashAccount.less';

interface Props {
    cashAccount: TCashAccount;
}

export const EditableCashAccount = observer(({ cashAccount }: Props) => {
    const inputRef = useRef<HTMLInputElement>(null);
    const [showForm, setFormVisibility] = useState(false);

    const showOrHideForm = useCallback(() => {
        setFormVisibility(!showForm);

        if (showForm) {
            inputRef.current?.focus();
        }
    }, [showForm]);

    const save = useCallback(() => {
        const newValue = inputRef.current?.value;

        if (newValue && newValue !== cashAccount.name) {
            updateCashAccount(cashAccount, newValue);
        }

        setFormVisibility(false);
    }, [cashAccount.name]);

    const deleteItem = useCallback(() => {
        deleteCashAccount(cashAccount.id);
    }, [cashAccount.id]);

    const onKeyDown = useCallback((event: KeyboardEvent<HTMLInputElement>) => {
        if (event.code === 'Escape') {
            setFormVisibility(false);
        }
        if (event.code === 'Enter') {
            save();
        }
    }, [save]);

    return <CashAccount
        cashAccount={cashAccount}
        nameSlot={showForm && <input
            ref={inputRef}
            name="name"
            onKeyDown={onKeyDown}
            defaultValue={cashAccount.name}
        />}
        buttonsSlot={
            showForm
                ? <div className="cash-account-buttons">
                    <button className="btn btn--small btn--no-background" onClick={deleteItem}>
                        <Icon iconName={IconEnum.delete} />
                    </button>
                    <button className="btn btn--small btn--no-background" onClick={save}>
                        <Icon iconName={IconEnum.ok} />
                    </button>
                </div>
                : <button className="btn btn--small btn--no-background" onClick={showOrHideForm}>
                    <Icon iconName={IconEnum.edit} />
                </button>
        }
    />;
});
