// frontend/src/pages/account/ui/RegisterPage.tsx
import { Link } from 'react-router';
import { RegisterForm } from '~/features/sign-up';

export function RegisterPage() {

    return <div className="register-page">
        <h1>Регистрация</h1>

        <RegisterForm>
            <div>
                <Link to="/login" className="link">Авторизация</Link>
            </div>
        </RegisterForm>
    </div>;
}

// frontend/src/pages/account/RegisterPage.vue
<template>
    <div class="register-page">
        <h1>Регистрация</h1>

        <RegisterForm>
            <div>
                <RouterLink :to="{name: 'login'}" class="link">
                    Авторизация
                </RouterLink>
            </div>
        </RegisterForm>
    </div>
</template>

<script setup lang="ts">
    import {RegisterForm} from '~/features/sign-up';
</script>

<style>
.register-page {
    max-width: 30rem;
}
</style>
