// frontend/src/widgets/transaction-history/ui/TransactionGroupTitle.tsx
import { DateTime } from '~/shared/utils';
import { useMemo } from 'react';
import './TransactionGroupTitle.less';

interface Props {
    date?: DateTime;
}

export const TransactionGroupTitle = ({ date }: Props) => {

    const formattedDate = useMemo(() => {
        if (!date) {
            return undefined;
        }

        return date.formatDateIfCurrentYear();
    }, [date]);

    if (!formattedDate) {
        return null;
    }

    return <div className="account-transaction-group-title">
        { formattedDate }
    </div>;
}

// frontend/src/widgets/transaction-history/ui/TransactionGroupTitle.vue
<template>
    <div
        v-if="formattedDate"
        class="account-transaction-group-title"
    >
        {{ formattedDate }}
    </div>
</template>

<script setup lang="ts">

    import { computed } from 'vue';
    import { DateTime } from '~/shared/utils';

    type TProps = {
        date?: DateTime;
    }

    const { date } = defineProps<TProps>();

    const formattedDate = computed(() => {
        if (!date) {
            return undefined;
        }

        return date.formatDateIfCurrentYear();
    });
</script>

<style>

.account-transaction-group-title {
    font-size: 18px;
    font-weight: bolder;
    padding: 1rem;
}
</style>
