// frontend/src/widgets/transaction-history/ui/TransactionsHistory.tsx
import { observer } from 'mobx-react-lite';
import { TransactionGroupTitle } from './TransactionGroupTitle.tsx';
import {
    AccountTransactionFn,
    AccountTransactionRequest,
    TAccountTransaction,
    TPaginatedAccountTransactions
} from '~/shared/api';
import { MouseEvent, useCallback, useEffect, useState } from 'react';
import { AccountTransaction } from '~/entities/account-transaction';
import { AccountTransactionsStore } from '~/entities/account-transaction';
import './TransactionsHistory.less';

export const TransactionsHistory = observer(() => {
    const [transactionList, setTransactionList] = useState<TAccountTransaction[]>([]);
    const [moreLink, setMoreLink] = useState<string | undefined>(undefined);

    const load = useCallback(async (event?: MouseEvent) => {
        event?.preventDefault();
        const response = await AccountTransactionRequest.load(moreLink);

        if (!response.ok) {
            return;
        }

        const jsonResponse = (await response.json()) as TPaginatedAccountTransactions;

        if (!jsonResponse.data) {
            return;
        }

        setTransactionList([
            ...transactionList,
            ...jsonResponse.data.map(item => AccountTransactionFn(item)),
        ]);
        setMoreLink(jsonResponse.links.next);
    }, [transactionList, moreLink]);

    /**
     * Отдаст дату, которую будем выводить для группировки транзакций по дням
     *
     * @param transaction
     * @param transactionIndexInList
     */
    const getDayGroupDate = useCallback((transaction: TAccountTransaction, transactionIndexInList: number) => {
        if (transactionIndexInList === 0) {
            return transaction.created_at;
        }

        const formatString = 'YYYY-MM-DD';
        const transactionDate = transaction.created_at.format(formatString);
        const previousTransaction = transactionList[transactionIndexInList - 1];
        const previousTransactionDate = previousTransaction.created_at.format(formatString);

        return transactionDate === previousTransactionDate
            ? undefined
            : transaction.created_at;
    }, [transactionList]);

    const accountTransactionsStore = AccountTransactionsStore.getInstance();

    useEffect(() => {
        load();
    }, []);

    useEffect(() => {
        if (accountTransactionsStore.needReloadTransactionsPage) {
            setMoreLink(undefined);
            load();
            accountTransactionsStore.reloaded();
        }
    }, [load, accountTransactionsStore.needReloadTransactionsPage]);

    return <div className="account-transaction-list">
        {
            transactionList.map((transaction, index) => {
                return <div key={transaction.id}>
                    <TransactionGroupTitle date={getDayGroupDate(transaction, index)} />
                    <AccountTransaction transaction={transaction}>
                        <>
                            {/*<DeleteTransactionButton :transaction="transaction as TAccountTransaction" />*/}
                            {/*<EditTransactionButton :transaction="transaction as TAccountTransaction" />*/}
                        </>
                    </AccountTransaction>
                </div>
            })
        }

        <a
            v-if="moreLink"
            href={moreLink}
            onClick={load}
        >
            Следующие
        </a>
    </div>;
});

// frontend/src/widgets/transaction-history/ui/TransactionsHistory.vue
<template>
    <div class="account-transaction-list">
        <div
            v-for="(transaction, index) in transactionList"
            :key="transaction.id"
        >
            <TransactionGroupTitle :date="getDayGroupDate(transaction, index)" />
            <AccountTransaction
                :transaction="transaction"
            >
                <template #buttons>
                    <DeleteTransactionButton :transaction="transaction" />
                    <EditTransactionButton :transaction="transaction" />
                </template>
            </AccountTransaction>
        </div>

        <a
            v-if="moreLink"
            :href="moreLink"
            @click.prevent="load(moreLink)"
        >
            Следующие
        </a>
    </div>
</template>

<script setup lang="ts">
    import { AccountTransactionRequest, TAccountTransaction, TPaginatedAccountTransactions } from '~/shared/api';
    import { ref, watch } from 'vue';
    import { AccountTransaction as AccountTransactionFn } from '~/shared/api';
    import { AccountTransaction, useAccountTransactionStore } from '~/entities/account-transaction';
    import { storeToRefs } from 'pinia';
    import DeleteTransactionButton from '~/features/edit-transaction/ui/DeleteTransactionButton.vue';
    import EditTransactionButton from '~/features/edit-transaction/ui/EditTransactionButton.vue';
    import TransactionGroupTitle from '~/widgets/transaction-history/ui/TransactionGroupTitle.vue';

    const transactionList = ref<TAccountTransaction[]>([]);
    const moreLink = ref<string | undefined>();

    async function load(link?: string) {
        const response = await AccountTransactionRequest.load(link);

        if (!response.response.value?.ok) {
            return;
        }

        const jsonResponse = await response.json<TPaginatedAccountTransactions>();

        if (!jsonResponse.data.value) {
            return;
        }

        if (link) {
            transactionList.value.push(
                ...jsonResponse.data.value.data.map(item => AccountTransactionFn(item)),
            );
        } else {
            transactionList.value = jsonResponse.data.value.data.map(item => AccountTransactionFn(item));
        }

        moreLink.value = jsonResponse.data.value.links.next;
    }

    load();

    const accountTransactionsStore = useAccountTransactionStore();
    const { needReload } = storeToRefs(accountTransactionsStore);

    watch(needReload, () => {
        if (needReload.value) {
            load();
            accountTransactionsStore.reloaded();
        }
    });

    /**
     * Отдаст дату, которую будем выводить для группировки транзакций по дням
     *
     * @param transaction
     * @param transactionIndexInList
     */
    function getDayGroupDate(transaction: TAccountTransaction, transactionIndexInList: number) {
        if (transactionIndexInList === 0) {
            return transaction.created_at;
        }

        const formatString = 'YYYY-MM-DD';
        const transactionDate = transaction.created_at.format(formatString);
        const previousTransaction = transactionList.value[transactionIndexInList - 1];
        const previousTransactionDate = previousTransaction.created_at.format(formatString);

        return transactionDate === previousTransactionDate
            ? undefined
            : transaction.created_at;
    }

</script>

<style>
.account-transaction-list {
    max-width: 50rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
}

</style>
