// frontend/src/entities/cash-account/ui/CashAccount.vue
<template>
    <div class="cash-account">{{ cashAccount.name }}</div>
</template>

<script setup lang="ts">
    import {TCashAccount} from '~/shared/api';

    type TProps = {
        cashAccount: TCashAccount
    }

    const { cashAccount } = defineProps<TProps>();

</script>

<style>
.cash-account {
    border: 1px solid var(--color-border);
    border-radius: 1rem;
    padding: 1rem;
    box-sizing: border-box;
}
</style>

// frontend/src/entities/cash-account/ui/CashAccount.tsx
import { ReactNode } from 'react';
import { observer } from 'mobx-react-lite';
import { TCashAccount } from '~/shared/api';
import './CashAccount.less';

interface Props {
    cashAccount: TCashAccount
    children?: ReactNode;
    nameSlot?: ReactNode;
    buttonsSlot?: ReactNode;
}

export const CashAccount = observer((props: Props) => {
    return <div className="cash-account">
        {
            props.nameSlot
                ? props.nameSlot
                : <div className="cash-account__name">
                    { props.cashAccount.name }
                </div>
        }
        <div className="cash-account__buttons">
            {props.buttonsSlot}
        </div>
    </div>;
});
